### ISSUE TITLE
New picking up emails and not recognized index in kibana

### ISSUE THREAD

**Issue by DZKeeper** [SpamScope/spamscope#10]
I have installed and configured everything using docker-compose.

I have no errors in the storm UI.

I assume the problem is that no mail seems to be picked up as the example email file remains in the folder, and the Kibana instance doesnt recognize the suggested index in my config.file.  

I have placed a raw email example as located [here](https://gist.githubusercontent.com/fedelemantuano/5dd702004c25a46b2bd60de21e67458e/raw/3fdff560c2c6078c416b959ca74567ddcb5470d6/1471832668.1377_3.ivanova.orig) in the "/mnt/mails" of my host.

my .env file looks like this:

```
CLUSTER_NAME=spamscope-cluster
DOCKER_MAILS_FOLDER=/mnt/mails
ELASTIC_DATA=/usr/share/elasticsearch/data
ELASTIC_MEM_LIMIT=2g
ELK_BIND_IP=127.0.0.1
ELK_TAG=5.6.3
HEAP_SIZE=1024m
HOST_MAILS_FOLDER=/mnt/mails
HOST_SPAMSCOPE_CONF=/etc/spamscope/
KIBANA_MEM_LIMIT=2g
NET_NAME=esnet
NODE_NAME=spamscope
SPAMSCOPE_BIND_IP=127.0.0.1
SPAMSCOPE_IMAGE_NAME=fmantuano/spamscope-elasticsearch
SPAMSCOPE_MEM_LIMIT=4g
```

Where to start Troubleshooting ?

Thanks for your time.

**Comment by fedelemantuano** [comment]
SpamScope can read from many folders that you have to set in configuration file.
You have to set [this part](https://github.com/SpamScope/spamscope/blob/develop/conf/spamscope.example.yml#L24) of configuration file. Remember that in case of Docker, these are paths in Docker container.

```
test: 
            mail_server: hostname
            # Trust string is used to get sender IP address from mail server.
            # More details: https://github.com/SpamScope/mail-parser/blob/v0.4.6/mailparser/__init__.py#L221
            trust_string: "test_trust_string"
            files_pattern: "*untroubled*"
            priority: 1
            path_mails: /path/mails1```

In this example you have:
 - test mailbox
 - files_pattern every file with untroubled in the middle (random_untroubled_random)
 - priority 1 means that these mails are analyzed before than sothers (priority 100 is very low priority)
 - path_mails is the path of your mails for this mailbox

You can read more details [here](https://github.com/SpamScope/spamscope/wiki/Configuration).

Kibana doesn't see index because there aren't mails in Elasticsearch.

**Comment by DZKeeper** [comment]
I got it to go... Thanks. My email file did not fit the pattern specified in the config.
